security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\Centro:
      algorithm: auto
    App\Entity\Cliente:
      algorithm: auto
  providers:
    centro_provider:
      entity:
        class: App\Entity\Centros
        property: email_centro
    cliente_provider:
      entity:
        class: App\Entity\Clientes
        property: email_cliente
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: centro_provider
      form_login:
        login_path: login
        check_path: login
        always_use_default_target_path: true
        username_parameter: email_centro
      logout:
        path: app_logout
        target: /
    cliente:
      lazy: true
      provider: cliente_provider
      form_login:
        login_path: cliente_login
        check_path: cliente_login
        always_use_default_target_path: true
        username_parameter: email_cliente
      logout:
        path: app_logout
        target: /

  access_control:

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
